version: "2"
services:
  frontend:
    build: ./frontend/app.py
    links:
      - db
    ports:
      - "3000:3000"
  backend:
    build: ./backend/server.py
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql
    ports: 
      - "32000:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root