version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  frontend:
    build: ./frontend/
    links:
      - db
    ports:
      - "3000:3000"
  backend:
    build: ./backend/
    depends_on:
      - db
    ports:
      - "5000:5000"
  
